export const sagaActions = {
  SET_LOADING: "SET_LOADING",
  FETCH_CAFES: "FETCH_CAFES",
  CREATE_CAFE: "CREATE_CAFE",
  UPDATE_CAFE: "UPDATE_CAFE",
  DELETE_CAFE: "DELETE_CAFE",
  FETCH_EMP: "FETCH_EMP",
  FETCH_CAFE_EMP: "FETCH_CAFE_EMP",
  CREATE_EMP: "CREATE_EMP",
  UPDATE_EMP: "UPDATE_EMP",
  DELETE_EMP: "DELETE_EMP",
};
